package entities;
// Generated Mar 6, 2019 1:15:47 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "demo")
public class Order implements java.io.Serializable {

	private Integer id;
	private Date datacreation;
	private String name;
	private boolean status;
	private int accountid;
	private Set<Orderdetail> orderdetails = new HashSet<Orderdetail>(0);

	public Order() {
	}

	public Order(Date datacreation, String name, boolean status, int accountid) {
		this.datacreation = datacreation;
		this.name = name;
		this.status = status;
		this.accountid = accountid;
	}

	public Order(Date datacreation, String name, boolean status, int accountid, Set<Orderdetail> orderdetails) {
		this.datacreation = datacreation;
		this.name = name;
		this.status = status;
		this.accountid = accountid;
		this.orderdetails = orderdetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datacreation", nullable = false, length = 10)
	public Date getDatacreation() {
		return this.datacreation;
	}

	public void setDatacreation(Date datacreation) {
		this.datacreation = datacreation;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "accountid", nullable = false)
	public int getAccountid() {
		return this.accountid;
	}

	public void setAccountid(int accountid) {
		this.accountid = accountid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<Orderdetail> getOrderdetails() {
		return this.orderdetails;
	}

	public void setOrderdetails(Set<Orderdetail> orderdetails) {
		this.orderdetails = orderdetails;
	}

}
